#sdk: "/Users/chronosafe/.rvm/gems/ruby-1.9.3-p545@rho/gems/rhodes-4.0.0"
sdkversion: 4.0.0
name: mapping
version: 1.0
vendor: rhomobile
build: debug
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator7.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.mapping
  BundleURLScheme: mapping
wp:
  productid: '177ab720-b20e-0131-7255-38f6b11557a9'
symbian:
  uid: '0xe81a3c2a'
android:
  version: 2.3.3

extensions: ["rhoconnect-client"]
